project_id = "isjxzxgakkjzcabhqhva"

[functions.seed-database]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false
