project_id = "cnmtxswjkeqfhxflsvug"

[functions.delete-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.admin-reports]
verify_jwt = false

[functions.seed-database]
verify_jwt = false

[functions.export-database]
verify_jwt = false
